using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using SoundFlowSystem.Data;
using UnityEngine;

namespace SoundFlowSystem.Libraries
{
    public static class SoundsCollectionConstantGenerator
    {
        public static void GenerateClassFile(string path, string prefix, SoundData[] soundsData)
        {
            // Validate everything before creating directories or replacing a file.
            var source = GenerateSource(prefix, soundsData);
            var root = Path.GetFullPath(Application.dataPath);
            var relativePath = (path ?? string.Empty).Replace('\\', '/').TrimStart('/');
            var directory = Path.GetFullPath(Path.Combine(root, relativePath));
            if (!string.Equals(directory, root, StringComparison.OrdinalIgnoreCase)
                && !directory.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
                throw new ArgumentException("The output directory must be inside Assets.", nameof(path));
            Directory.CreateDirectory(directory);
            File.WriteAllText(Path.Combine(directory, (prefix ?? string.Empty) + "SoundsCollectionConstants.cs"), source, new UTF8Encoding(false));
#if UNITY_EDITOR
            UnityEditor.AssetDatabase.Refresh();
#endif
        }

        public static string GenerateSource(string prefix, SoundData[] soundsData)
        {
            if (soundsData == null) throw new ArgumentNullException(nameof(soundsData));
            var className = (prefix ?? string.Empty) + "SoundsCollectionConstants";
            if (!IsIdentifier(className)) throw new ArgumentException("Prefix must form a valid C# identifier.", nameof(prefix));
            var names = new HashSet<string>(StringComparer.Ordinal) { className };
            var keys = new HashSet<string>(StringComparer.Ordinal);
            var sb = new StringBuilder();
            sb.AppendLine("// Generated by SoundFlowSystem.");
            sb.AppendLine("namespace App.SoundFlowSystem.Libraries");
            sb.AppendLine("{");
            sb.AppendLine("    public static class " + className);
            sb.AppendLine("    {");
            foreach (var sound in soundsData)
            {
                if (sound == null || string.IsNullOrWhiteSpace(sound.Key))
                    throw new ArgumentException("Every sound must have a non-empty key.", nameof(soundsData));
                if (!keys.Add(sound.Key)) throw new ArgumentException($"Duplicate sound key '{sound.Key}'.", nameof(soundsData));
                var name = ConvertToPascalCase(sound.Key);
                if (!names.Add(name)) throw new ArgumentException($"Sound key '{sound.Key}' produces duplicate identifier '{name}'.", nameof(soundsData));
                sb.AppendLine($"        public static readonly string {name} = \"{EscapeString(sound.Key)}\";");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string ConvertToPascalCase(string input)
        {
            var result = new StringBuilder();
            bool start = true;
            foreach (var character in input)
            {
                if (!char.IsLetter(character) && !char.IsDigit(character))
                {
                    start = true;
                    continue;
                }
                if (result.Length == 0 && char.IsDigit(character)) result.Append('_');
                result.Append(start ? char.ToUpperInvariant(character) : char.ToLowerInvariant(character));
                start = false;
            }
            if (result.Length == 0) throw new ArgumentException($"Sound key '{input}' does not contain an identifier.");
            return result.ToString();
        }

        private static bool IsIdentifier(string value)
        {
            if (value.Length == 0 || !(char.IsLetter(value[0]) || value[0] == '_')) return false;
            foreach (var character in value)
                if (!(char.IsLetterOrDigit(character) || character == '_')) return false;
            return true;
        }

        private static string EscapeString(string value)
        {
            var result = new StringBuilder();
            foreach (var character in value)
            {
                switch (character)
                {
                    case '\\': result.Append("\\\\"); break;
                    case '"': result.Append("\\\""); break;
                    case '\r': result.Append("\\r"); break;
                    case '\n': result.Append("\\n"); break;
                    case '\t': result.Append("\\t"); break;
                    default:
                        if (char.IsControl(character) || character == '\u2028' || character == '\u2029')
                            result.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
                        else result.Append(character);
                        break;
                }
            }
            return result.ToString();
        }
    }
}
